= OpenLCB Asciidoc POC

Proof of Concept for tooling and workflows for publishing OpenLCB and NMRA LCC standards via Asciidoc and Maven.

== Prerequisites

- https://maven.apache.org[Maven]
- https://graphviz.gitlab.io[Graphviz] (to generate diagrams)
- A raw text editor (https://code.visualstudio.com[Visual Studio Code] is recommended)

== Installation

=== Linux

TBD

=== macOS

1. Install https://brew.sh[Homebrew]
2. `brew install maven graphviz`

=== Windows

TBD

== Usage

NOTE: Maven automatically manages dependencies other than those listed above. Therefor, when a dependency is updated in the pom.xml file, the next use of Maven will require internet access.

Maven has a default _phase_ and default _profile_. In the POC, the _phase_ can be ignored, but profiles are used to control how documents are rendered.

=== Generate Documents

==== All Documents as Drafts
....
mvn
....
or
....
mvn -P draft
....
The generated documents and intermediate outputs will be in `target/generated-docs`.

==== All Documents as OpenLCB Published Documents
....
mvn -P openlcb
....

==== All Documents as NMRA Published Documents
....
mvn -P nmralcc
....

==== Specific Document(s)
....
mvn -D openlcb.doc=<document>
....
`<document>` is the full document name relative to the source directory (`src`). This can be combined with profiles to update a single document with specific rendering (e.g., `mvn -P draft -D openlcb.doc=datagram-transport-s.adoc`).

=== Remove Generated Content
....
mvn clean
....

== Stylesheets

This project (currently) uses the default XSLT stylesheets for DocBook with parameters and titlepage customizations specified in a profile-dependent stylesheet.

=== Title Pages

The title page templates are `src/resources/openlcb-fo-titlepage.templates.xml` and `src/resources/nmralcc-fo-titlepage.templates.xml`. These can be edited in any editor, but need to be processed from XMl into XSL to be used as stylesheets.

==== Processing

===== Linux and macOS

From the root of this project:
....
mvn
./src/resources/proc-titlepage.sh
....

===== Windows

TBD

=== References

- http://www.sagehill.net/docbookxsl/PdfBookmarks.html[DocBook XSL: The Complete Guide]
- http://docbook.sourceforge.net/release/xsl/current/doc/index.html[DocBook XSL Stylesheets: Reference Documentation]
